### ISSUE TITLE
Thanks for your idea

### ISSUE THREAD

**Issue by liudongmiao** [commonsguy/cwac-crossport#2]
When I'm figuring for android support design without appcompat, cwac influenced me.

However, I don't like to modify android support design.

So I just make a simple appcompat-dummy, which make android support design works.

And for myself, as I only use Snackbar and TabLayout, I remove other components, which save 20K or so.

You can refer dummy codes here: https://github.com/brevent/Brevent/tree/master/appcompat-dummy .

```
        compile project(':appcompat-dummy')
        compile("com.android.support:design:${rootProject.supportLibraryVersion}") {
            exclude group: 'com.android.support', module: 'appcompat-v7'
        }
```

As I said, I only make sure snackbar and tablayout works, and for other components like fab and textinput, there should some modification for appcomat-dummy.

**Comment by commonsguy** [comment]
Thanks for the information!

In the future, though, please use the issue tracker for issues. I have [other options](https://github.com/commonsguy/cwac-crossport#questions) for things that are not issues.
